FROM node:buster
COPY create_random_file.mjs .

RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
RUN node --experimental-modules create_random_file.mjs
# Just comment next line and everything will build successfully.
RUN node --experimental-modules create_random_file.mjs

ENTRYPOINT ["node", "-version"]
